### ISSUE TITLE
Como reseteo la energia neta importada o exportada

### ISSUE THREAD

**Issue by olvelasco** [MiguelAngelLV/balance_neto#1]
Seria interesante que los días 1 de cada mes se reseteara el contador total de energía neta importada y exportada de forma que coincida con la facturación de la distribuidora

**Comment by MiguelAngelLV** [comment]
Buenas.

Eso depende de cada uno, hay gente que reinicia a mitad de mes, depende de cuándo empieces el contrato. Los que tenemos FV si vamos a mes natural, pero el resto no.

Puedes usar un utility meter para crear otra entidad con en reinicio cuando te convenga de forma muy fácil.


Además recuerda que desde el Energy Dashboard pues verlo por día, semana y mes.
