### ISSUE TITLE
1 Sensor para todo

### ISSUE THREAD

**Issue by pardal12** [MiguelAngelLV/balance_neto#10]
Hola,
Mi inversor Fronius solo me indica 1 solo sensor para la red eléctrica donde en positivo me indica que consumo de la red y en negativo cuando vierto.
Desconozco la manera de conseguir los dos sensores para la aplicación.
Me podrías ilustrar?
Gracias

**Comment by MiguelAngelLV** [comment]
Estás mirando el consumo «actual», o lo que es lo mismo, watts, tienes que mirar el consumo acumulado, normalmente, en kilowattios/hora.

Los fronius también lo tienen, que es lo que necesita el Energy Dashboard por ejemplo.
