### ISSUE TITLE
Feature Rquest: Usage in Portugal (15min periods)

### ISSUE THREAD

**Issue by FragMenthor** [MiguelAngelLV/balance_neto#11]
Hello! And first of all, thanks for your work.
I live in Portugal, and here we have netmettering, but every 15min starting from the 0 minute every hour. How can we apply this to our syestem? Would it be possible to have the time period configurable?
Thanks in advance! :)

**Comment by MiguelAngelLV** [comment]
Um... Maybe can add a configuration option. Give a few days ;)

**Comment by MiguelAngelLV** [comment]
I upload a new beta with 1/4 hour option

**Comment by FragMenthor** [comment]
Wow, thanks!!! :)
