### ISSUE TITLE
Feature Request: Additional balance calculation before full hour

### ISSUE THREAD

**Issue by Jordan87** [MiguelAngelLV/balance_neto#12]
Hi Miguel

As you alredy know im facing issue that in avarege one every other day calculation for balance your "Net Balance" component is doing calculation for entity "Net Exported" and "Net Imported" few/several seconds to late and Energy calculation sometimes is incorrect because of missing value for full houer and next one is accumulated for two hours.
![image](https://github.com/MiguelAngelLV/balance_neto/assets/10414918/7b57d812-4083-4633-89aa-0a54cb62d3f0)
![image](https://github.com/MiguelAngelLV/balance_neto/assets/10414918/4046ea53-a25e-4402-982e-8492e5a04791)
Now when I'm using multitariffs (diffrent prices for different hours during day/weekend) its evem more important to have proper energy usage in Energy tab.

I have some idea which probably can be easy implement in your addon/component. :)
May be you can perform two calculations before every full hour? Now it should be done 5 seconds before every full hour but in some cases (at lest for me it slightle delayed and done after full hour but is it doable to perform two calcolatios, one for example 20seconds before full hour and second calculation lets say 2 seconds before which will update "Net Exported" and "Net Imported" value?

Thanks :)

**Comment by MiguelAngelLV** [comment]
I am working in configurable version so you will could set the offset you want ;)

**Comment by MiguelAngelLV** [comment]
Added configurable offset in new beta ;)

**Comment by Jordan87** [comment]
Thank You

I will experiment with different values :)

btw
Any idea why sometimes there is so big delay in calculation by your component?
Most of the time it was spot on 5 seconds vbefore full hour but not always. Can we do something to put higher prio for that component? :)

**Comment by MiguelAngelLV** [comment]
I think the problem is HA overhead. 

HA use a queue of task. Each task is added a queue and they will resolve in order. If any task need a lot of time, the next task will need wait it...

These is the reason for security offset.
