### ISSUE TITLE
Deprecated constants

### ISSUE THREAD

**Issue by antonio-fiol** [MiguelAngelLV/balance_neto#14]
Hi, I'm getting these two error messages in the log. After searching that there was no other issue with the same content, I am creating one per HA instructions:

- STATE_CLASS_TOTAL_INCREASING was used from balance_neto, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please create a bug report at https://github.com/MiguelAngelLV/balance_neto/issues
- DEVICE_CLASS_ENERGY was used from balance_neto, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please create a bug report at https://github.com/MiguelAngelLV/balance_neto/issues

Thank you for a great component!!

**Comment by githchema** [comment]
Same problem here. It becomes somewhat annoying when going through the logs.
Great job Miguel, I follow you in all your contributions.

**Comment by MiguelAngelLV** [comment]
Fixed.
