### ISSUE TITLE
Habilitar estadisticas para entidades.

### ISSUE THREAD

**Issue by miguelangel-nubla** [MiguelAngelLV/balance_neto#17]
Las entidades que genera la integración no se registran en el componente de estadísticas a largo plazo de HA.
Mirándolo por encima parece que [falta la propiedad `state_class`.](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)

**Comment by MiguelAngelLV** [comment]
De las 3, se registran 2. La única que no se registra es el balance neto «actual», porque realmente no hace falta.

Exportado Neto e Importado Neto sí están con state_class

Se puede ver aquí: 
https://github.com/MiguelAngelLV/balance_neto/blob/main/custom_components/balance_neto/sensor.py#L30

**Comment by miguelangel-nubla** [comment]
Tienes razón, exportado neto e importado neto no se registraban en mi instalación por otro motivo ajeno a la integración.

Entiendo que cuando dices que no hace falta para el balance neto "actual" es porque es la suma por horas de los otros dos sensores?
¿En ese caso, cual seria la forma de recrear los valores pasados?
Un sensor de platilla solo funcionaria a partir del momento que se crea dicho sensor, y tocar la base de datos directamente no suele ser buena idea.

**Comment by MiguelAngelLV** [comment]
El actual me refiero a que tienes «ahora mismo», en plan «En esta hora tienes 1.5kWh a tu favor», la idea es ver si te estás pasando o no para realizar automatizaciones, pero una vez pasada la esa hora, no te interesa, solo te interesa el resultado, que se habrá sumado en importación o exportación.

Desgraciadamente, los valores pasados no vas a poder obtenerlos si no es tocando la base de datos, y no de forma sencilla precisamente (tienes que hacer restas y sumas por agrupaciones...) Normalmente saldría mejor exportar todo a un CSV y calcularlo usando excel.

**Comment by miguelangel-nubla** [comment]
La intención es utilizar el historial del sensor balance neto para:
 - Explorar la posibilidad de predecir la situación del próximo periodo basado en los datos históricos.
 - Comparar el valor de los picos por horas con el consumo por horas registrado por mi contador/distribuidora.

Para ambos casos es mucho mas sencillo utilizar los valores del balance neto ya que registra los incrementos en lugar de los totales.
Más concretamente, en el caso de utilizarlos para predicción, la tendencia que solo refleja el sensor balance neto dentro de una hora (Amplitud y dirección) también sería de utilidad.

De ahí el interés en tener a mano los datos a largo plazo del balance neto.

¿Consideras añadir también el `state_class` a balance neto ?
Siempre existe la posibilidad de excluir la entidad de la integración `recorder` totalmente, pero por el contrario no es trivial añadir las estadísticas a largo plazo manualmente.
Si consideras que no es la mejor opción para la integración, no hay problema, buscaré una alternativa.

**Comment by MiguelAngelLV** [comment]
El problema es que los datos estadísticos de guardan por horas, si que solo tendrás el máximo, minimo y  medida de la hora.

Si te vale lo puedo añadir en una siguiente actualización.

**Comment by miguelangel-nubla** [comment]
Me vale, gracias.

**Comment by MiguelAngelLV** [comment]
Ya lo tienes :)

**Comment by miguelangel-nubla** [comment]
Gracias!
