### ISSUE TITLE
Importar datos anteriores

### ISSUE THREAD

**Issue by armanplex** [MiguelAngelLV/balance_neto#2]
Hola y gracias por tu trabajo, ayuda mucho en optimizar la fotovoltaica. 

¿Puedes indicarme como importo los datos del panel de energia de meses anteriores para que no pierda datos y seguir a partir de ahora con los de balance neto?

gracias

**Comment by MiguelAngelLV** [comment]
Tendrías que acceder a la base de datos, buscar las la estadísticas en metadata y después cambiarle el metadata_id de la tabla de estadísticas de la antigua a la nueva, o duplicar las filas, ya según al gusto.

Después tendrás que corregir los datos donde pasa de uno a otro desde la sección de estadísticas propia de HA porque tendrás unos picazos enormes.
