### ISSUE TITLE
after update cpu +20% UP

### ISSUE THREAD

**Issue by oomichalekoo** [MiguelAngelLV/balance_neto#22]
after update cpu +20% UP

**Comment by oomichalekoo** [comment]
Entity sensor.energia_bilans_netto (<class 'custom_components.balance_neto.sensor.BalanceSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/MiguelAngelLV/balance_neto/issues

**Comment by MiguelAngelLV** [comment]
New update that would fix the problem.

**Comment by oomichalekoo** [comment]
Now i dont instal first ;-) wgl will try IT and comment here?

**Comment by nepozs** [comment]
@oomichalekoo 
You should do it first :P (as OP of this issue).

**Comment by oomichalekoo** [comment]
Updated and watching

**Comment by mariuszxeno** [comment]
> New update that would fix the problem.
HI @MiguelAngelLV 
Thank you very much, the fix solves the problem. Good job.

**Comment by oomichalekoo** [comment]
Dont working MSI cubix N100

**Comment by MiguelAngelLV** [comment]
Um... @oomichalekoo 1.5.1  or 1.5.2?

**Comment by oomichalekoo** [comment]
1.52

**Comment by MiguelAngelLV** [comment]
Um... I see... after fews hours, the problem returns...

**Comment by MiguelAngelLV** [comment]
Publish 1.6

Tested during 10h without any issue.
