### ISSUE TITLE
Sensores importación y exportación neta a 0

### ISSUE THREAD

**Issue by jmayoralas** [MiguelAngelLV/balance_neto#27]
Acabo de instalar esta integración en HA y me encuentro que con los sensores de importación y exportación no están funcionando.

Los he configurado según estos sensores de la entidad Power Meter que se configura al instalar la integración de mi inversor Huawei SUN2000:

![Captura de pantalla de 2024-07-06 13-42-49](https://github.com/MiguelAngelLV/balance_neto/assets/20075656/c2e6d05c-9556-496f-b893-06619d658199)

![Captura de pantalla de 2024-07-06 13-47-36](https://github.com/MiguelAngelLV/balance_neto/assets/20075656/3318c7b4-f103-460d-a521-1c6a8798c7e1)

Sin embargo los sensores que genera tu integración están planos a 0 kWh:

![Captura de pantalla de 2024-07-06 13-43-18](https://github.com/MiguelAngelLV/balance_neto/assets/20075656/a7bfc696-c7ec-4742-9d6f-540fe9cb069e)

![Captura de pantalla de 2024-07-06 13-47-09](https://github.com/MiguelAngelLV/balance_neto/assets/20075656/0f3c8806-7c29-4b01-8cbf-a493971eb148)

Seguramente esté haciendo yo algo mal, pero a ver si me puedes orientar dónde puede estar el problema.

**Comment by MiguelAngelLV** [comment]
Los datos de actualizan cada hora. Si lo acabas de llover es normal que aún estén a 0.

**Comment by jmayoralas** [comment]
Perfecto !

![Captura de pantalla de 2024-07-06 14-10-24](https://github.com/MiguelAngelLV/balance_neto/assets/20075656/a617f409-34b3-43d4-8878-48315a4caf4a)

Perdona haberte molestado con esta tontería. Las prisas son malas consejeras. Buenísima integración, por cierto. :+1:

**Comment by MiguelAngelLV** [comment]
Nada, tranquilo.

Llevo un tiempo probando una opción para poder ir actualizando poco a poco en vez de cada hora. A ver cuando lo termino de verificar que funciona correctamente y lo aplico.
