### ISSUE TITLE
Valor erróneo

### ISSUE THREAD

**Issue by jjvelar** [MiguelAngelLV/balance_neto#3]
Hola!
Gracias por la integración.
En ocasiones sale un valor muy loco en los sensores de exportación e importación neta (-500000 o +500000).
Adjunto captura de pantalla.
Gracias!

![image](https://github.com/MiguelAngelLV/balance_neto/assets/47498098/579ed95f-1f24-4400-8432-f45ef03b9806)

**Comment by MiguelAngelLV** [comment]
Jums... ¿Podrías mirar que valores tienes en el sensor original?

Quizás el sensor original se resetea por algún motivo o se queda como desconocido y es lo que provoca todo el problema.

**Comment by jjvelar** [comment]
Efectivamente el sensor original da un salto muy grande provocado por un error puntual en los datos originales.
¿Puedo sugerir que tus sensores incluyan un filtro de manera que si el valor de entrada es undefined, unavailable o, en valor absoluto es mayor que, por ejemplo, 100000, devuelva 0, por ejemplo?
 Saludos,

José

**Comment by MiguelAngelLV** [comment]
Pues si se podría poner que el caso de cambio anormal decida omitir el
cambio.

Mañana a la tarde te subo una beta para que la pruebes.

**Comment by jjvelar** [comment]
Perfecto!

**Comment by jjvelar** [comment]
> Pues si se podría poner que el caso de cambio anormal decida omitir el cambio. Mañana a la tarde te subo una beta para que la pruebes.

Hola!
Tengo que hacer algo para descargar la beta y probarla?
Gracia y un saludo,

José

**Comment by MiguelAngelLV** [comment]
Perdona, lo modifiqué y lo dejé probando y olvidé subirlo y avisarte.

Ya está subido. Simplemente en el HACS ve al repo y darle a descargar, en el selector de versión, activa «versiones prueba» o algo así y deberia salirte la beta.

**Comment by MiguelAngelLV** [comment]
Básicamente descarto por «diferencia».

De esta forma mato dos pájaros de un tiro.

Si está como no disponible, no llegan valores, y en cuanto llegue el primero, habrá mucha diferencia (desde 0...) y por tanto descarta y empieza a calcular de nuevo.

Básicamente, siempre que la diferencia sea de más de 100kWh (no creo que nadie palme 100kWh use HA para llevar el cálculo) descarta el cálculo que lleva y empieza a contar.

**Comment by jjvelar** [comment]
Totalmente de acuerdo.
