### ISSUE TITLE
Values take too much to update

### ISSUE THREAD

**Issue by nportillo2** [MiguelAngelLV/balance_neto#4]
Values update randomly, some times doesn't reset on time, so you can not trust.

**Comment by MiguelAngelLV** [comment]
The data is reset when it get the first value in the new hour. If you data update slow, the component too.

**Comment by MiguelAngelLV** [comment]
The new version reset the balance without wait the new value. Check if it works better now.

**Comment by nportillo2** [comment]
You were totally right; value updates when source updates. But there was the problem with the hh:00 reset that I can confirm it is solved now, so everything works perfect right now! Thank You very much, it's very helpfull to me, I'm using it to squeeze every watt!

**Comment by MiguelAngelLV** [comment]
Great!
