### ISSUE TITLE
Error en el registro

### ISSUE THREAD

**Issue by Vicente-Ch** [MiguelAngelLV/balance_neto#5]
Hola. En el registro me aparecen dos errores:
Este error se originó a partir de una integración personalizada.

Logger: homeassistant
Source: custom_components/balance_neto/sensor.py:180
Integration: Balance Neto (documentation, issues)
First occurred: 19:27:35 (1 occurrences)
Last logged: 19:27:35

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/balance_neto/sensor.py", line 64, in update_import
    grid_balance.update_import(new_state)
  File "/config/custom_components/balance_neto/sensor.py", line 180, in update_import
    value = float(state.state)
            ^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

Este error se originó a partir de una integración personalizada.

Logger: homeassistant
Source: custom_components/balance_neto/sensor.py:193
Integration: Balance Neto (documentation, issues)
First occurred: 19:27:35 (1 occurrences)
Last logged: 19:27:35

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/balance_neto/sensor.py", line 67, in update_export
    grid_balance.update_export(new_state)
  File "/config/custom_components/balance_neto/sensor.py", line 193, in update_export
    value = float(state.state)
            ^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

**Comment by MiguelAngelLV** [comment]
Parece que tu sensor está devolviendo datos inválidos y da error.

Sacaré una versión que verifique el dato antes de intentar transformarlo.

**Comment by Vicente-Ch** [comment]
Oh. Gracias

**Comment by MiguelAngelLV** [comment]
Comprueba la nueva versión a ver si te elimina los problemas.

**Comment by Vicente-Ch** [comment]
Ya no da errores. Gracias por la rapidez

**Comment by MiguelAngelLV** [comment]
Perfecto!
