### ISSUE TITLE
Two instalaltions (dos instalaciones)

### ISSUE THREAD

**Issue by marioJR1979** [MiguelAngelLV/balance_neto#7]
In my case, I have two photovoltaic installations controlled with Home Assistant and unified in the ENERGIA control panel. When I put the second one, entities do not appear and I understand that it is not integrated into the energy panel.
Is there a way to do it or to include it in your integration?

En mi caso, tengo dos instalaciones fotovoltaicas controladas con Home Assistant y unificadas en el panel de control de ENERGIA. Cuando meto la segunda no me aparecen entidades y entiendo que no se integra en el panel de energía.
¿Habría alguna manera de hacerlo o de que lo incluyese en su integración?

Regards.

**Comment by MiguelAngelLV** [comment]
Pues depende. ¿Ambas instalaciones están en la misma red? Si es así, lo más fácil sería que hicieras un template para el exportar y el importar dónde se sumen ambas instalaciones (Exportar A+B e Importar A+B), y que esos sean los sensores que usa el componente.

Si la instalación son de distintos sitios, realmente no sabría decirte como funcionaría el balance neto ahí, Supongo que se tratarían como distintas y en unos sumarías y en otros no...  Pero tampoco estoy seguro.

**Comment by marioJR1979** [comment]
Buenas. Muchas gracias por contestar. 

Ambas intalaciones están en la misma red de datos, pero en distintas redes electricas, es decir, son dos puntos de suministros diferentes, con lo que cada una tiene su balance neto diferente. Si las sumara se compensaría una con la otra pero realmente, al ser dos puntos de suministro diferentes, no sería real, por lo que no debería hacerlo así. Tengo las dos instalaciones electricas unficadas en el panel de control de ENERGIA, ya que no puedo poner dos paneles de ENERGIA, una para cada instalación, en Home Assistant, o no sé como hacerlo. Por eso le comentaba si se podia tener entidades diferentes para ambas instalaciones, pero entiendo que no se integrarían correctamente en el panel de ENERGIA.

Muchas gracias, un saludo.

**Comment by MiguelAngelLV** [comment]
Lo único que se me ocurre es modifica el sensor para que puedas añadirlo dos veces.

**Comment by marioJR1979** [comment]
Diculpa mi ignoracía, pero ¿a qué sensor te refieres?. Tengo dos instalaciones cada una con su lectura de consumo y de excedentes. No se si terefieres a crear dos Balances Netos con tu addon, pero es que eso es lo que no me deja.
Gracias.
Un saludo.

**Comment by MiguelAngelLV** [comment]
Si, me refería a eso. A modificar el componente para que te lo permita. Eso
solucionaría el problema?

**Comment by MiguelAngelLV** [comment]
Perfecto. Estoy haciendo pruebas de que todo funciona correctamente.

**Comment by MiguelAngelLV** [comment]
He subido una versión beta a ver que tal te va.

Desde HACS selecciona «ver betas» y te debería salirte la 1.3-Beta.

**Comment by marioJR1979** [comment]
He instalado la 1.3 beta3 y configurado. Voy a probar un tiempo, aun que algo ya no me cuadra en los valores, quiza por que no estoy introduciendo las entidades idoneas para el calculo. Tengo que hacer algunas pruebas.

Oye, que gran curro. Muchas gracias.

**Comment by MiguelAngelLV** [comment]
Debes introducir los valores totales de kWh que te da el inversor (los que no se reinician por día ni nada).

**Comment by marioJR1979** [comment]
Ok. Creo que los valores que tengo puestos son los correctos. Voy a darle un tiempo pq no lleva puesto ni 1 hora.

Un saludo.

**Comment by marioJR1979** [comment]
Despues de un par de días de pruebas aún tengo muchas dudas de que funcione correctamente. 
Lo primero es saber interpretar el valor de Balance neto. ¿Cunado es positivo entiendo que se esta consuminedo más que se esta vertiendo a la red?. Ya no estoy ni seguro. 
Por otro lado me da unos valores de Balance neto muy altos, a veces de +99 Kwh y otras tambien de -99 kWh cuando mis instalaciones son de 15 Kw de potencia en placas. No tiene mucho sentido.
Tambien indicar que al configurar el addon, en una instalación me ha cogido los valores de exportación neta e importacion neta con unos valores antiguos, entioendo que porque ya tenía puesto el addon de antes en esa instalacion, , y en la otra ha empezado de cero. Tampo se muy bien como interpretar estos valores ya que son acumulativos y quiza fuera más interesante que fueran por hora.

Bueno, espero haberme explicado.

Un saludo.

**Comment by MiguelAngelLV** [comment]
Primero, aunque parece una tontería, no es un addon, es un componente, son cosas distintas ;)

El componente crea 3 entidades.

El Balance Neto es tu balance en la hora actual.  Puede ser negativo o positivo según cuanto hayas importado/exportado en lo que llevas de hora. Por ejemplo, si has importado 1kWh y has exportado 4, el balance será de +3kWh.

Como bien dices, valores +99 a -99 no es normal. Tiendo a pensar que no has seleccionado los sensores correctos.
Los sensores a usar son los del inversor que solo «suben». Debería ser kwh importados y kwh exportados, valores que solo van hacia arriba (no se reinician ni nada).

Los valores por hora no tendrían sentido, ya que cada hora solo subiría un valor (o importado o exportado), que es la «gracia» del balance neto, y para eso, ya está la propia entidad Balance Neto.

Básicamente, al terminar cada hora, si el balance neto es positivo se lo suma a exportados y si es negativo se lo suma a importados, por tanto, solo aumenta uno de los dos sensores.

Si activas el modo debug en el componente y reinicias, este empezará a guardar información sobre los distintos valores. Pasado un día, vuelves a pulsar y te descargará toda la información al respecto para poder analizarla (que valores daba cada sensor, el cálculo hecho...).

Si puedes, sería de ayuda tener este informe para intentar localizar el problema.

**Comment by marioJR1979** [comment]
Disculpa, no sabía como llamarlo; addons,, plugin,... Me queda claro, componente.

Lo voy a poner en modo debug, a ver si sé, y te paso el inform para que le des un vistazo. Me gustaría darte un buen feedback para que te sea de utilidad. 

Un saludo, gracias.

**Comment by marioJR1979** [comment]
[home-assistant_balance_neto_2023-09-07T23-46-20.654Z.log](https://github.com/MiguelAngelLV/balance_neto/files/12554211/home-assistant_balance_neto_2023-09-07T23-46-20.654Z.log)

Adjunto el log de debug. A ver si tu puedes sacar alguna conclusion.

Un saludo.

**Comment by MiguelAngelLV** [comment]
Veo que tienes dos;

- smart_meter_nave_arquetas_energia_real_*
- smart_meter_nave_ja_energia_real_*

Y la que está haciendo cosas raras es arquetas, ja parece ir bien.

Los valores de -99 a 99 es porque se pasa del límite que puse para casos de errores  y se reinicia.

Creo que el problema es arquetas está dando los valores en wattios hora en vez de kilovattios hora, ¿Podría ser?

Porque los cálculos los hace bien, es que aumentan muchímo los valores entre cada dato:

 A las 00:00
>2023-09-08 00:00:20.863 DEBUG (SyncWorker_11) [custom_components.balance_neto.sensor] Import (sensor.smart_meter_nave_arquetas_energia_real_plus): 11646242

A las 01:00
>2023-09-08 01:00:20.843 DEBUG (SyncWorker_0) [custom_components.balance_neto.sensor] Import (sensor.smart_meter_nave_arquetas_energia_real_plus): 11646601


11646601 - 11646242 = 359

Entiendo que no has consumido 359kWh en una hora, no?

Comprueba si tienes otros sensores que sean kwh en vez de wh o sino, simplemente crea un nuevo sensor que de los valores en kwh usando un template.

**Comment by marioJR1979** [comment]
Buenas.

Entra la las 0:00 y la 1:00 esa instación no consume ni 1 Kw/h normalmente. 

Voy a cambiar algunos parametros y recomfiguro y te cuento.

Un saludo, gracias.

**Comment by marioJR1979** [comment]
Buena.

Efectivamente la segunda instalación estaba en Wh. Lo he cambiado y ahora los valores son más coherentes. 

Muchas gracias. Eres un crack.

Un saludo.
