### ISSUE TITLE
Contadores diarios

### ISSUE THREAD

**Issue by 8eholder** [MiguelAngelLV/balance_neto#9]
Mi Inversor entrega los datos de la importación/exportación total con un solo decimal y la diaria con dos y por eso estaba intentando usar ese dato.
El problema es que en el cambio de dia y al volver a 0 los contadores diarios del inversor los valores volcados al cambiar de dia son erroneos.

¿Se puede corregir o mejor uso los contadores totales aunque pierda resolucion?

**Comment by MiguelAngelLV** [comment]
Creo que podría modificar el componente para que funcione con sensores que se resetean... Después te subo una beta.

**Comment by MiguelAngelLV** [comment]
Solucionado en la 1.3.1.

Prueba la versión a ver si te funciona correctamente.

**Comment by 8eholder** [comment]
Si, creo que se ha resuelto

Esta es la grafica de ayer:
![image](https://github.com/MiguelAngelLV/balance_neto/assets/73500374/3585bb61-2256-4b10-9051-916ee0157f15)

Y esta la de hoy ya con la version nueva:

![image](https://github.com/MiguelAngelLV/balance_neto/assets/73500374/18659292-17c6-4f9e-8356-32adbd655729)

Muchas gracias por tu trabajo.
